name: acme

channels:
- conda-forge

dependencies:
- python=3.9
- cupy
- jax==0.4.3
- cudatoolkit==11.6.2
- cudnn
- dm-acme
- pip
- pymunk
- ipykernel
- ipywidgets
- black

- pip:
  - gym[accept-rom-license] # for testing `r2d2.py`
